In [10]:
import pandas as pd
import numpy as np

In [11]:
# Load data
df = pd.read_csv('../raw/energy_data_global.csv')

In [12]:
df.head(10)

,timestamp,building_id,sensor_id,temperature,humidity,power_consumption
0,2025-10-03T09:00:00Z,B004,S03,24.1,60.9,740.0
1,2025-10-03T03:00:00Z,B004,S03,24.8,50.9,811.0
2,2025-10-03T18:00:00Z,B009,S02,16.8,73.7,690.0
3,2025-10-03T15:00:00Z,B002,S01,18.0,62.7,554.0
4,2025-10-04T12:00:00Z,B006,S02,20.4,59.0,695.0
5,2025-10-02T09:00:00Z,B009,S02,24.8,52.5,746.0
6,2025-10-04T21:00:00Z,B002,S01,17.0,61.9,561.0
7,2025-10-04T18:00:00Z,B007,S03,15.0,63.4,562.0
8,2025-10-04T18:00:00Z,B007,S01,16.8,66.7,647.0
9,2025-10-01T18:00:00Z,B001,S02,NaN,68.3,522.0

In [13]:
df.describe()

       temperature     humidity  power_consumption
count  1194.000000  1196.000000        1198.000000
mean     20.934003    58.041890         697.680301
std       3.872204     6.661277         161.629987
min     -10.000000    41.500000         -50.000000
25%      17.500000    52.900000         619.000000
50%      21.000000    58.000000         687.000000
75%      24.400000    63.400000         759.000000
max      28.400000    74.800000        2500.000000

In [14]:
df = df.dropna()
df.describe()

       temperature     humidity  power_consumption
count  1188.000000  1188.000000        1188.000000
mean     20.932912    58.025673         698.040404
std       3.873595     6.668042         162.110153
min     -10.000000    41.500000         -50.000000
25%      17.500000    52.800000         619.750000
50%      20.950000    58.000000         687.000000
75%      24.425000    63.400000         760.000000
max      28.400000    74.800000        2500.000000

In [15]:
# Suppression des consommations négatives
df = df[df['power_consumption'] >= 0]
df.describe()

       temperature    humidity  power_consumption
count  1187.000000  1187.00000        1187.000000
mean     20.936310    58.01786         698.670598
std       3.873456     6.66541         160.716068
min     -10.000000    41.50000         380.000000
25%      17.500000    52.80000         620.000000
50%      21.000000    58.00000         687.000000
75%      24.450000    63.40000         760.000000
max      28.400000    74.80000        2500.000000

In [16]:
# Suppression des consommations négatives
df = df[df['temperature'] >= 0]
df.describe()

       temperature     humidity  power_consumption
count  1185.000000  1185.000000        1185.000000
mean     20.988523    58.018903         698.693671
std       3.661916     6.660030         160.838160
min      14.000000    41.500000         380.000000
25%      17.500000    52.800000         620.000000
50%      21.000000    58.000000         687.000000
75%      24.500000    63.400000         760.000000
max      28.400000    74.800000        2500.000000

In [17]:
# ecart interquantile pour determiner un seuil max
Q1 = df['power_consumption'].quantile(0.25)
Q3 = df['power_consumption'].quantile(0.75)
IQR = Q3 - Q1
upper_limit = Q3 + 1.5 * IQR
df = df[df['power_consumption'] < upper_limit]
df.describe()

       temperature     humidity  power_consumption
count  1176.000000  1176.000000        1176.000000
mean     20.985204    58.040731         687.969388
std       3.661487     6.655336          96.846476
min      14.000000    41.500000         380.000000
25%      17.500000    52.900000         619.000000
50%      21.000000    58.000000         686.000000
75%      24.500000    63.400000         758.250000
max      28.400000    74.800000         963.000000

In [18]:
# Sauvegarde des données
df.to_csv('../processed/clean_global.csv', index=False)